version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart:
      always
    ports:
      - "8080:8080"
    volumes:
      - .:/data
    image: neketli/promo-bot
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./data/sqlite:/root/db/
      