name: Build and Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neketli/promo-bot/promo-bot
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets. GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest

      - name: Deploy package to server
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets. GITHUB_TOKEN }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN, TG_TOKEN, DB_CONNECTION
          script: |
            docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull ghcr.io/neketli/promo-bot/promo-bot:latest
            docker stop containername
            docker system prune -f
            docker run -e TG_TOKEN=$TG_TOKEN -e DB_CONNECTION=$DB_CONNECTION --name containername -dit -p 8080:8080 ghcr.io/neketli/promo-bot/promo-bot:latest